ENVIRONMENT: "local"
SERVER_PORT: "8081"
MYSQL_HOST: "localhost"
MYSQL_PORT: "3306"
MYSQL_BD: "sigecan2"
MYSQL_USER: "dev_seek"
MYSQL_PASSWORD: "dev@2024"
MYSQL_SCHEMA: "sigecan"
SECURITY_API_LEVEL_ENABLED: "true"
JWT_BASE64_SECRET_KEY: "EpvZNqUROVAJFM3pWj8Rscfem7YfuoJ3V59ud+INim3yIpnoYpk8GEB0t5+Ux93kBEqnguDzCuXUrcz1K/kUJw=="
